import { state } from './state.js';
import { updateNav } from '../components/nav.js';
import { trackView } from './analytics.js';

const VIEW_MODULES = {
  'hub':        () => import('../views/hub.js'),
  'my-tasks':   () => import('../views/my-tasks.js'),
  'kanban':     () => import('../views/kanban.js'),
  'locations':  () => import('../views/locations.js'),
  'schedule':   () => import('../views/schedule.js'),
  'team':       () => import('../views/team.js'),
  'equipment':  () => import('../views/equipment.js'),
  'budget':     () => import('../views/budget.js'),
  'timeline':   () => import('../views/timeline.js'),
  'calendar':   () => import('../views/calendar.js'),
};

// Route aliases — backwards compatibility for old bookmarks/links.
// "contacts" was merged into "locations" with a tab system.
const ROUTE_ALIASES = {
  'contacts': { route: 'locations', defaultTab: 'contacts' },
};

const cache = {};

function parseHash() {
  const hash = window.location.hash.slice(1) || 'hub';
  const [route, qs] = hash.split('?');
  const params = {};
  if (qs) {
    qs.split('&').forEach(pair => {
      const [k, v] = pair.split('=');
      if (k) params[decodeURIComponent(k)] = decodeURIComponent(v || '');
    });
  }
  return { route, params };
}

export function getRoute() {
  const { route, params } = parseHash();
  const alias = ROUTE_ALIASES[route];
  if (alias) {
    // Only apply alias-default if user did NOT specify ?tab=… explicitly
    const explicitTab = params.tab;
    const tabToSet = explicitTab || alias.defaultTab;
    if (tabToSet) localStorage.setItem('locations_active_tab', tabToSet);
    return alias.route;
  }
  // Even for non-alias routes: respect ?tab=… on locations
  if (route === 'locations' && params.tab) {
    localStorage.setItem('locations_active_tab', params.tab);
  }
  return route;
}

export async function navigate(route, forceRerender = false) {
  if (!state.loaded) return;
  const container = document.getElementById('view-container');
  if (!container) return;

  container.classList.add('fade-out');
  await new Promise(r => setTimeout(r, 150));

  if (route !== 'locations') state.activeFilter = 'all';

  const loader = VIEW_MODULES[route] || VIEW_MODULES['hub'];
  if (!cache[route] || forceRerender) cache[route] = await loader();
  const html = await cache[route].default();

  // eslint-disable-next-line no-unsanitized/property -- HTML strings generated by trusted view modules in this codebase
  container.innerHTML = html;
  container.classList.remove('fade-out', 'animate-slideUp');
  // Re-trigger animation: force reflow then add class
  void container.offsetWidth;
  container.classList.add('animate-slideUp');

  updateNav(route);

  if (route === 'kanban' && !state.editMode) {
    cache['kanban'].initKanbanDragAndDrop();
  }

  if (route === 'my-tasks') {
    cache['my-tasks'].initMyTasksSwipe();
  }

  if (window.lucide) window.lucide.createIcons();

  // Engagement signal
  try { trackView(route); } catch { /* ignore */ }
}

window.addEventListener('hashchange', () => navigate(getRoute()));
