import { state } from './state.js';
import { updateNav } from '../components/nav.js';

const VIEW_MODULES = {
  'hub':        () => import('../views/hub.js'),
  'my-tasks':   () => import('../views/my-tasks.js'),
  'kanban':     () => import('../views/kanban.js'),
  'locations':  () => import('../views/locations.js'),
  'schedule':   () => import('../views/schedule.js'),
  'team':       () => import('../views/team.js'),
  'equipment':  () => import('../views/equipment.js'),
  'budget':     () => import('../views/budget.js'),
  'timeline':   () => import('../views/timeline.js'),
  'contacts':   () => import('../views/contacts.js'),
  'calendar':   () => import('../views/calendar.js'),
};

const cache = {};

export function getRoute() {
  return window.location.hash.slice(1) || 'hub';
}

export async function navigate(route, forceRerender = false) {
  if (!state.loaded) return;
  const container = document.getElementById('view-container');
  if (!container) return;

  container.classList.add('fade-out');
  await new Promise(r => setTimeout(r, 150));

  if (route !== 'locations') state.activeFilter = 'all';

  const loader = VIEW_MODULES[route] || VIEW_MODULES['hub'];
  if (!cache[route] || forceRerender) cache[route] = await loader();
  const html = await cache[route].default();

  // eslint-disable-next-line no-unsanitized/property -- HTML strings generated by trusted view modules in this codebase
  container.innerHTML = html;
  container.classList.remove('fade-out');
  container.classList.add('animate-slideUp');
  // Remove animation class after it completes so it can be re-applied
  container.addEventListener('animationend', () => {
    container.classList.remove('animate-slideUp');
  }, { once: true });

  updateNav(route);

  if (route === 'kanban' && !state.editMode) {
    cache['kanban'].initKanbanDragAndDrop();
  }

  if (window.lucide) window.lucide.createIcons();
}

window.addEventListener('hashchange', () => navigate(getRoute()));
