/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './js/views/**/*.js',
    './js/components/**/*.js',
  ],
  theme: {
    screens: {
      'xs': '480px',
      'sm': '640px',
      'md': '769px',
      'lg': '1024px',
      'xl': '1280px',
    },
    extend: {
      colors: {
        bg:      'var(--c-bg)',
        bg2:     'var(--c-bg2)',
        card:    'var(--c-card)',
        card2:   'var(--c-card2)',
        txt:     'var(--c-text)',
        txt2:    'var(--c-text2)',
        muted:   'var(--c-muted)',
        border:  'var(--c-border)',
        border2: 'var(--c-border2)',
        purple:  { DEFAULT: '#6c3fc5' },
        violet:  'var(--c-violet)',
        lilac:   'var(--c-lilac)',
        accent:  'var(--c-accent)',
        gold:    'var(--c-gold)',
        green:   'var(--c-green)',
        blue:    'var(--c-blue)',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        '2xl': '48px',
      },
      borderRadius: {
        'DEFAULT': '14px',
        'sm': '8px',
        'xs': '4px',
        'full': '99px',
      },
      fontFamily: {
        sans: ['-apple-system', 'Segoe UI', 'system-ui', 'sans-serif'],
        mono: ['SF Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        'xs': '0.7rem',
        'sm': '0.8rem',
        'base': '0.95rem',
        'md': '1.05rem',
        'lg': '1.25rem',
        'xl': '1.5rem',
        '2xl': '1.8rem',
        '3xl': '2.2rem',
      },
      boxShadow: {
        'sm': '0 1px 3px rgba(0,0,0,.2), 0 1px 2px rgba(0,0,0,.15)',
        'DEFAULT': '0 4px 12px rgba(0,0,0,.2), 0 2px 4px rgba(0,0,0,.15)',
        'md': '0 8px 24px rgba(0,0,0,.25), 0 4px 8px rgba(0,0,0,.15)',
        'lg': '0 16px 48px rgba(0,0,0,.3), 0 8px 16px rgba(0,0,0,.2)',
        'focus': '0 0 0 3px rgba(155,93,229,.5)',
      },
      transitionDuration: {
        'fast': '150ms',
        'base': '200ms',
        'medium': '250ms',
        'slow': '300ms',
      },
      keyframes: {
        fadeIn:    { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp:  { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:  { from: { opacity: '0', transform: 'scale(0.92)' }, to: { opacity: '1', transform: 'scale(1)' } },
        pulse:    { '0%,100%': { boxShadow: '0 0 0 4px rgba(247,37,133,.2)' }, '50%': { boxShadow: '0 0 0 8px rgba(247,37,133,.1)' } },
        'pulse-glow': { '0%,100%': { boxShadow: '0 0 4px rgba(247,37,133,.2)' }, '50%': { boxShadow: '0 0 12px rgba(247,37,133,.4)' } },
        'skeleton-pulse': { '0%': { backgroundPosition: '200% 0' }, '100%': { backgroundPosition: '-200% 0' } },
        shake:    { '0%,100%': { transform: 'translateX(0)' }, '25%': { transform: 'translateX(-2px)' }, '75%': { transform: 'translateX(2px)' } },
      },
      animation: {
        fadeIn:    'fadeIn 300ms ease',
        slideUp:  'slideUp 300ms ease forwards',
        scaleIn:  'scaleIn 300ms ease',
        pulse:    'pulse 2s infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'skeleton-pulse': 'skeleton-pulse 1.5s ease-in-out infinite',
        shake:    'shake 300ms ease',
      },
      maxWidth: {
        'content': '1320px',
        'main': '1200px',
      },
    },
  },
  plugins: [],
};
