/**
 * Bottom Sheet Component
 * Reusable slide-up panel with drag-to-dismiss and snap points.
 */

let sheetEl = null;
let backdropEl = null;
let startY = 0;
let currentY = 0;
let sheetHeight = 0;
let isDragging = false;
let onDismissCallback = null;

const SNAP_THRESHOLD = 0.4; // dismiss if dragged past 40% of sheet height

/**
 * Opens a bottom sheet with the given content.
 * @param {string} content - Trusted HTML string (internal only, never user-generated input)
 * @param {object} options
 */
export function openBottomSheet(content, { onDismiss, title } = {}) {
  if (sheetEl) closeBottomSheet();
  onDismissCallback = onDismiss || null;

  // Backdrop
  backdropEl = document.createElement('div');
  backdropEl.className = 'bottom-sheet-backdrop';
  backdropEl.addEventListener('click', closeBottomSheet);

  // Sheet container
  sheetEl = document.createElement('div');
  sheetEl.className = 'bottom-sheet';

  // Build DOM safely — handle, title, content
  const handle = document.createElement('div');
  handle.className = 'bottom-sheet-handle';
  handle.setAttribute('aria-hidden', 'true');
  handle.appendChild(document.createElement('span'));
  sheetEl.appendChild(handle);

  if (title) {
    const titleEl = document.createElement('div');
    titleEl.className = 'bottom-sheet-title';
    titleEl.textContent = title;
    sheetEl.appendChild(titleEl);
  }

  const contentEl = document.createElement('div');
  contentEl.className = 'bottom-sheet-content';
  // Content is trusted internal HTML (nav items generated by our own code)
  contentEl.innerHTML = content;
  sheetEl.appendChild(contentEl);

  document.body.appendChild(backdropEl);
  document.body.appendChild(sheetEl);
  document.body.style.overflow = 'hidden';

  // Trigger animations
  requestAnimationFrame(() => {
    backdropEl.classList.add('show');
    sheetEl.classList.add('show');
    sheetHeight = sheetEl.offsetHeight;
  });

  // Touch gestures on handle area
  handle.addEventListener('touchstart', onTouchStart, { passive: true });
  handle.addEventListener('touchmove', onTouchMove, { passive: false });
  handle.addEventListener('touchend', onTouchEnd, { passive: true });

  // Also allow dragging from the whole sheet top area
  sheetEl.addEventListener('touchstart', onSheetTouchStart, { passive: true });
  sheetEl.addEventListener('touchmove', onSheetTouchMove, { passive: false });
  sheetEl.addEventListener('touchend', onSheetTouchEnd, { passive: true });

  if (window.lucide) window.lucide.createIcons();
}

export function closeBottomSheet() {
  if (!sheetEl) return;

  sheetEl.classList.remove('show');
  sheetEl.classList.add('dismiss');
  backdropEl.classList.remove('show');

  setTimeout(() => {
    sheetEl?.remove();
    backdropEl?.remove();
    sheetEl = null;
    backdropEl = null;
    document.body.style.overflow = '';
    if (onDismissCallback) onDismissCallback();
  }, 250);
}

export function isBottomSheetOpen() {
  return sheetEl !== null;
}

// ── Touch handling ──────────────────────────────────────────────

function onTouchStart(e) {
  startY = e.touches[0].clientY;
  isDragging = true;
  sheetEl.style.transition = 'none';
}

function onTouchMove(e) {
  if (!isDragging) return;
  currentY = e.touches[0].clientY - startY;
  if (currentY < 0) currentY = 0;
  sheetEl.style.transform = `translateY(${currentY}px)`;
  e.preventDefault();
}

function onTouchEnd() {
  if (!isDragging) return;
  isDragging = false;
  sheetEl.style.transition = '';

  if (currentY > sheetHeight * SNAP_THRESHOLD) {
    closeBottomSheet();
  } else {
    sheetEl.style.transform = '';
  }
  currentY = 0;
}

function onSheetTouchStart(e) {
  const rect = sheetEl.getBoundingClientRect();
  const touchYInSheet = e.touches[0].clientY - rect.top;
  if (touchYInSheet > 60) return;
  onTouchStart(e);
}

function onSheetTouchMove(e) {
  if (!isDragging) return;
  onTouchMove(e);
}

function onSheetTouchEnd() {
  if (!isDragging) return;
  onTouchEnd();
}
